### ISSUE TITLE
求联系方式

### ISSUE THREAD

**Issue by jacobjiangwei** [summertian4/Sparrow#33]
coderfish@163.com

你有微信吗 加我qq也可以 110773265

**Comment by summertian4** [comment]
您好，是有什么 Sparrow 的技术问题吗，我还木有开发完哟

**Comment by jacobjiangwei** [comment]
是想问你有没有兴趣加入我们 微博留言没反应

发自我的 iPhone

**Comment by summertian4** [comment]
Sorry，这两天木有注意到微博，我现在去看看😄
